# Site settings
title: בחדרי מאמרים
subtitle: פודקאסט על מאמרים
email: shakedzy@gmail.com
ophir_email: osarusi@gmail.com
description:  פודקאסט בעברית על מאמרים בתחומי דאטה-סיינס ולמידת מכונה. אופיר סרוסי ושקד זיכלינסקי מציגים בכל פרק מאמר אחד מהתחום שבאמת כדאי להכיר, מפרקים אותו ומרכיבים אותו מחדש תוך כדי שיחה.
full_name: Shaked Zychlinski and Ophir Sarusi
baseurl: "/jc-podcast" # the subpath of your site, e.g. /blog
url: "https://shakedzy.xyz" # the base hostname & protocol for your site
google_analytics: UA-141245946-1
logo: "/assets/images/logo.jpg"
favicon: "/assets/images/favicon.png"
twitter_username: "@shakedzy"

social_banner: 
  image: "/assets/images/logo.jpg"
  type: "image/jpeg"
  height: 968
  width: 968

# Build settings
include: ["_pages"]
markdown: kramdown

exclude: [LICENSE, LICENSE-CODE.md, LICENSE-IMAGES, README.md, MAKE_YOUR_OWN.md, bower.json]
